In [2]:
import pandas as pd
import numpy as np

# MYSQL DB conn

In [3]:
import mysql.connector

In [4]:
try:
    mydb = mysql.connector.connect(host='rel-fa.sandisk.com',
                               port=,
                               user='', 
                               password='',
                               database='')

    mycursor = mydb.cursor()
    mycursor.execute("SHOW Tables")
    for x in mycursor:
        print(x)
except Exception as e:
    print("Error: ",e)

('CFA_Failures_SAILR',)
('CFA_Keywords_SAILR',)


In [5]:
CFA_failure = pd.read_sql("Select * from CFA_Failures_SAILR",mydb)
CFA_failure


C:\Users\1000311006\AppData\Local\Temp\ipykernel_19472\939044381.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  CFA_failure = pd.read_sql("Select * from CFA_Failures_SAILR",mydb)


idFail_Analysis   Jira_Number Failure_Category  \
0                    2   RMAEXT-2013       Controller   
1                    3   RMAEXT-2036       Controller   
2                    4   RMAEXT-2037       Controller   
3                    5   RMAEXT-2038       Controller   
4                    6   RMAEXT-2088      Application   
...                ...           ...              ...   
12194            17305   RMAFA-10467              NTF   
12195            17307    SSDFA-2635      Application   
12196            17309  ESSDFA-27435        Component   
12197            17310  ESSDFA-27436        Component   
12198            17311   RMAFA-10469      Application   

             Failure_Subcategory  \
0             Transient Bit Flip   
1             Transient Bit Flip   
2             Transient Bit Flip   
3             Transient Bit Flip   
4                    Over Cycled   
...                          ...   
12194           No Trouble Found   
12195  Improper Command Sequence   
12196         Temperature Sensor   
12197         Temperature Sensor   
12198                    ESD/EOS   

                                              FA_Summary  \
0      GAT part read from PFMU address 0x34405A that ...   
1      one bit flip is occurred at iGAT delta list. T...   
2      – one bit flip is occurred at VC delta in MST....   
3      believe that corruption (bit-flip) occurred in...   
4      Memory has been cycled beyond its endurance li...   
...                                                  ...   
12194  Random blocks were put through erase/program/r...   
12195  Initial FA\r\nDrive manufacturing history was ...   
12196  Initial FA\r\nDrive manufacturing history was ...   
12197  Initial FA\r\nManufacturing history was review...   
12198                 Decap show EOS damage on the ASIC.   

                                       Corrective_Action  \
0      A new firmware to address this issue is now av...   
1      A new firmware to address this issue is now av...   
2      A new firmware to address this issue is now av...   
3      A new firmware is available which addresses th...   
4      Corrective action cannot be generated for this...   
...                                                  ...   
12194                                                N/A   
12195                          N/A - Application related   
12196  N/A - Corrective action cannot be determined f...   
12197  Corrective action cannot be determined for thi...   
12198  Corrective action cannot be generated for this...   

                   Customer     Product_Line Product_Type_or_Project  \
0                       LGE            iNAND                   Whale   
1                       LGE            iNAND                   Whale   
2                       LGE            iNAND                   Whale   
3                       LGE            iNAND                    PC2E   
4           Magneti-Marelli          MicroSD                 MicroSD   
...                     ...              ...                     ...   
12194                   SIE             NAND                    NAND   
12195  Applied Data Systems  L-W eSSD Non-JV                   Omaha   
12196      The Aurora Group         L-S eSSD                  Malibu   
12197      The Aurora Group         L-S eSSD                  Malibu   
12198                 Tesla          MicroSD                 MicroSD   

      PowerOn_Hours Grown_Bad_Blocks Max_Temp Host_Writes Replication_Temp  \
0              None             None     None        None             None   
1              None             None     None        None             None   
2              None             None     None        None             None   
3              None             None     None        None             None   
4              None             None     None        None             None   
...             ...              ...      ...         ...              ...   
12194          None             None

In [6]:
CFA_failure.shape

(12198, 16)

In [7]:
CFA_failure = CFA_failure.dropna(subset=['FA_Summary'])
CFA_failure

idFail_Analysis  Jira_Number Failure_Category Failure_Subcategory  \
0                    2  RMAEXT-2013       Controller  Transient Bit Flip   
1                    3  RMAEXT-2036       Controller  Transient Bit Flip   
2                    4  RMAEXT-2037       Controller  Transient Bit Flip   
3                    5  RMAEXT-2038       Controller  Transient Bit Flip   
4                    6  RMAEXT-2088      Application         Over Cycled   
...                ...          ...              ...                 ...   
12193            17298  RMAFA-10463              NTF    No Trouble Found   
12194            17299  RMAFA-10464              NTF    No Trouble Found   
12195            17304  RMAFA-10466              NTF    No Trouble Found   
12196            17305  RMAFA-10467              NTF    No Trouble Found   
12197            17311  RMAFA-10469      Application             ESD/EOS   

                                              FA_Summary  \
0      GAT part read from PFMU address 0x34405A that ...   
1      one bit flip is occurred at iGAT delta list. T...   
2      – one bit flip is occurred at VC delta in MST....   
3      believe that corruption (bit-flip) occurred in...   
4      Memory has been cycled beyond its endurance li...   
...                                                  ...   
12193  Random blocks were put through erase/program/r...   
12194  Reported blocks were put through erase/program...   
12195  Random blocks were put through erase/program/r...   
12196  Random blocks were put through erase/program/r...   
12197                 Decap show EOS damage on the ASIC.   

                                       Corrective_Action         Customer  \
0      A new firmware to address this issue is now av...              LGE   
1      A new firmware to address this issue is now av...              LGE   
2      A new firmware to address this issue is now av...              LGE   
3      A new firmware is available which addresses th...              LGE   
4      Corrective action cannot be generated for this...  Magneti-Marelli   
...                                                  ...              ...   
12193                                                N/A              SIE   
12194                                                N/A              SIE   
12195                                                N/A              SIE   
12196                                                N/A              SIE   
12197  Corrective action cannot be generated for this...            Tesla   

      Product_Line Product_Type_or_Project PowerOn_Hours Grown_Bad_Blocks  \
0            iNAND                   Whale          None             None   
1            iNAND                   Whale          None             None   
2            iNAND                   Whale          None             None   
3            iNAND                    PC2E          None             None   
4          MicroSD                 MicroSD          None             None   
...            ...                     ...           ...              ...   
12193         NAND                    NAND          None             None   
12194         NAND                    NAND          None             None   
12195         NAND                    NAND          None             None   
12196         NAND                    NAND          None             None   
12197      MicroSD                 MicroSD          None             None   

      Max_Temp Host_Writes Replication_Temp FA_Arrived_Date FA_Completed_Date  
0         None        None             None      2015-01-12        2015-01-20  
1         None        None             None      2015-01-19        2015-01-22  
2         None        None             None      2015-01-19        2015-01-22  
3         None        None             None      2015-01-19        2015-01-22  
4         None        None             None      2015-02-16        2015-02-17  
...        ...         ...              ...

In [18]:
CFA_failure.to_csv('upd_CFA_failure.csv',index=False)


# GET CSV OF CFA_FAILURES

In [4]:
CFA_failure = pd.read_csv('CFA_failure.csv')

In [5]:
CFA_failure[CFA_failure['Customer']=="Apple"]

idFail_Analysis  Jira_Number  Failure_Category  \
230                234  RMAEXT-2060          Assembly   
231                235  RMAEXT-2060          Assembly   
899                987         1528            Memory   
917               1005         1522       Write Abort   
924               1012         1529               CND   
...                ...          ...               ...   
11659            16653  RMAFA-10217          Assembly   
11667            16661  RMAFA-10219               CND   
11715            16730  RMAFA-10259               CND   
11753            16800  RMAFA-10276  Customer Related   
11903            17096  RMAFA-10368            Memory   

               Failure_Subcategory  \
230                       Cosmetic   
231                       Cosmetic   
899          Abnormal Distribution   
917                    Write Abort   
924            Could Not Duplicate   
...                            ...   
11659              Particle Damage   
11667                       Memory   
11715                       Memory   
11753            Cracked / Damaged   
11903  Power Down Wait Time Defect   

                                              FA_Summary  \
230    EMI coating glue residue sticking on the botto...   
231    EMI coating glue residue sticking on the botto...   
899    Abnormal ROMBLOCK Distribution caused an inval...   
917    read fails due to skipped pages/UECCs in UB LG...   
924    The failure mode reported by the customer was ...   
...                                                  ...   
11659  Apple DVT Qual unit (from program X2819) faile...   
11667  • Initial State\r\n- 10 RV_Fail blocks (1490~1...   
11715  Please see attached Apple report:\r\n1) S5E 10...   
11753  Initial State\r\n- From system log: Massive ES...   
11903  Failure Info\r\nWD_TLC_3D_G5_2P_512Gb_2DP, ASI...   

                                       Corrective_Action Customer  \
230    1, Set up program on current STI to capture th...    Apple   
231    1, Set up program on current STI to capture th...    Apple   
899    A read screen will be added to production test...    Apple   
917                                                  NaN    Apple   
924                                                  NaN    Apple   
...                                                  ...      ...   
11659                                                NaN    Apple   
11667                                                NaN    Apple   
11715                                                NaN    Apple   
11753                                                NaN    Apple   
11903                                           low DPPM    Apple   

      Product_Line Product_Type_or_Project PowerOn_Hours Grown_Bad_Blocks  \
230            PPN                     PPN           NaN              NaN   
231            PPN                     PPN           NaN              NaN   
899           NAND                    NAND           NaN              NaN   
917           SDFS                    SDFS           NaN              NaN   
924           NAND                    NAND           NaN              NaN   
...            ...                     ...           ...              ...   
11659          S5E                     S5E           NaN              NaN   
11667          S5E                     S5E           NaN              NaN   
11715          S5E                     S5E           NaN              NaN   
11753          S5E                     S5E           NaN              NaN   
11903          S5E                     S5E           NaN              NaN   

      Max_Temp Host_Writes Replication_Temp FA_Arrived_Date FA_Completed_Date  
230        NaN         NaN              NaN      2015-01-29        2015-02-05  
231        NaN         NaN              NaN      2015-01-29        2015-02-05  
899        NaN         NaN              NaN      2015-01-09        2015-02-03  
917        NaN         NaN              NaN      2015-01-08        201

In [7]:
#CFA_failure.drop(columns=['Unnamed: 0'],inplace=True,axis=1)
CFA_failure = CFA_failure.sample(frac=0.1,random_state = 42)
CFA_failure

idFail_Analysis  Jira_Number Failure_Category      Failure_Subcategory  \
6137              8053  CSSDFA-1065      Application    Mechanical Overstress   
4672              5872   RMAFA-5903           Memory  Temperature Sensitivity   
10452            14558   RMAFA-9538         Firmware       Free Block Release   
6498              8808  CSSDFA-1263         Assembly          Missing Process   
429                433  RMAEXT-2212           Memory    Marginal Read Failure   
...                ...          ...              ...                      ...   
6998              9517   RMAFA-7810           Memory        Select Gate Issue   
3118              3537   RMAFA-4816           Memory          Word Line Short   
2184              2424          NaN              NTF         No Trouble Found   
2039              2171  RMAEXT-2546              CND      Could Not Duplicate   
7092              9644   RMAFA-7897  Production Test   Test Program Bug/Issue   

                                              FA_Summary  \
6137                                Load switch cracked.   
4672   Write and then read at different temperatures ...   
10452  Based on RMAFA-9539\r\n\r\nInit passes but RO ...   
6498   Production line reject the device during assem...   
429    Memory errors in close proximity caused a doub...   
...                                                  ...   
6998   Trigger block issue: SGS Leak in commonly tied...   
3118   Word-line was found shorted to its adjacent Wo...   
2184   FA by SDKK: the unit was found to be fully fun...   
2039   on receipt it shows power short but after pFA ...   
7092   Using a memory tester which directly accesses ...   

                                       Corrective_Action  Customer  \
6137                                                 NaN        HP   
4672   Corrective action cannot be generated for this...     Avnet   
10452  BE branch : Lambeau_BiCS4_EdgeWlSkip_CC_ECCdis...    Lab126   
6498   1. Remove manual key-in hand written PCBA labe...    Satori   
429    Corrective action cannot be generated for this...      Edom   
...                                                  ...       ...   
6998   Screen approach:\r\n(1) Marking all common gro...     Apple   
3118   New production test screen of WL-WL leakage te...     Apple   
2184                                                 NaN   Fujitsu   
2039   Corrective action cannot be generated for this...  Zenitron   
7092   No retest of units will be performed until a c...    Huawei   

      Product_Line Product_Type_or_Project PowerOn_Hours Grown_Bad_Blocks  \
6137           SSD                     SSD           NaN              NaN   
4672          SDFS                    SDFS           NaN              NaN   
10452         SDFS                    SDFS           NaN              NaN   
6498           SSD                     SSD           NaN              NaN   
429          iNAND                   Whale           NaN              NaN   
...            ...                     ...           ...              ...   
6998           S4E                     S4E           NaN              NaN   
3118          NAND                    NAND           NaN              NaN   
2184          pSSD                    pSSD           NaN              NaN   
2039       MicroSD                 MicroSD           NaN              NaN   
7092          NAND                    NAND           NaN              NaN   

      Max_Temp Host_Writes Replication_Temp FA_Arrived_Date FA_Completed_Date  
6137       NaN         NaN              NaN      2018-04-18        2018-04-19  
4672       NaN         NaN              NaN      2017-03-17        2017-03-21  
10452      NaN         NaN              NaN      2022-05-11        2022-07-15  
6498       NaN         NaN              NaN      2018-08-22        2018-10-02  
429        NaN         NaN              NaN      2015-04-08        2015-04-25  
...        ...         ...              ...             ...        

# WORD TO JSON

In [8]:
import json

In [10]:

json_data = CFA_failure.to_json(orient='records')

with open('CFA_failure_output.json', 'w') as f:
    f.write(json_data)


with open("CFA_failure_output.json",mode='rt') as f:
    JIRA_dict = json.load(f)


# Quadrant VS

In [70]:
from llama_index.llms import ollama
from pathlib import Path
import qdrant_client
from llama_index.core import VectorStoreIndex, ServiceContext, download_loader, StorageContext,  Settings
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

In [61]:
JSON_reader = download_loader("JSONReader")
loader = JSON_reader()
json_docs = loader.load_data(Path('CFA_failure_output.json'))

C:\Users\1000311006\AppData\Local\Temp\ipykernel_97616\3653496544.py:1: DeprecationWarning: Call to deprecated function (or staticmethod) download_loader. (`download_loader()` is deprecated. Please install tool using pip install directly instead.)
  JSON_reader = download_loader("JSONReader")


In [93]:
json_docs

[Document(id_='36907cfc-d353-417c-b4d9-6c5a01e28a07', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, text='"idFail_Analysis": 8053,\n"Jira_Number": "CSSDFA-1065",\n"Failure_Category": "Application",\n"Failure_Subcategory": "Mechanical Overstress",\n"FA_Summary": "Load switch cracked.",\n"Corrective_Action": null,\n"Customer": "HP",\n"Product_Line": "SSD",\n"Product_Type_or_Project": "SSD",\n"PowerOn_Hours": null,\n"Grown_Bad_Blocks": null,\n"Max_Temp": null,\n"Host_Writes": null,\n"Replication_Temp": null,\n"FA_Arrived_Date": "2018-04-18",\n"FA_Completed_Date": "2018-04-19"\n"idFail_Analysis": 5872,\n"Jira_Number": "RMAFA-5903",\n"Failure_Category": "Memory",\n"Failure_Subcategory": "Temperature Sensitivity",\n"FA_Summary": "Write and then read at different temperatures causes issues with this memory.\\r\\nRead-all passed @ 25 degree.\\r\\nFail to read random LBAs @ -25 degree. ",\n"Corrective_Action": "Corrective action c

In [63]:
#Qdrant Client
client = qdrant_client.QdrantClient(path="./qdrant_data2")
vector_store = QdrantVectorStore(client=client, collection_name="CFA_failure")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

In [1]:
llm = Ollama(model="mistral:latest")#'llama3:latest'
#service_context = ServiceContext.from_defaults(llm=Ollama(model="mistral:latest"), embed_model="local")

Settings.llm = llm
Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
)

NameError: name 'Ollama' is not defined

In [91]:
index = VectorStoreIndex.from_documents(json_docs, storage_context=storage_context)
query_engine = index.as_query_engine()

In [95]:
print(
    query_engine.query(
        "What are the some of the issues faced by the client Apple"
        #"How to solve the EEPROM bit flip error?"
        #"What were some issues faced by the client Zenitron"
        #"what information can you provide regarding the issue faced by client Apple"
    )
)

 The client Apple encountered an issue related to charge trapping in the memory of their S4E product line. This issue was caused by heavy cycling within a short time period. Additionally, there was a failure recorded for Apple in the DPPM evaluation, which is either 0 (~11.5 DPPM without discounting the failure). The exact nature of this failure led to the conclusion that a test screen is not feasible for corrective action generation.


# Sentence Transformers

In [17]:
from sentence_transformers import SentenceTransformer
#from elasticsearch import Elasticsearch

RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (c:\Users\1000311006\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\__init__.py)

In [9]:
#model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
model2 = SentenceTransformer("Jaume/gemma-2b-embeddings")
#= SentenceTransformer("Alibaba-NLP/gte-Qwen2-1.5B-instruct", trust_remote_code=True) #SentenceTransformer("intfloat/e5-mistral-7b-instruct")

NameError: name 'SentenceTransformer' is not defined

In [42]:
#from numba import jit

embeddings_for_CFA_FA_SUM = []
#@jit(nopython=False)
def get_embeddings(JIRA_dict,model2):
    list1 = []
    for i in JIRA_dict: #["FA_Summary"]
        #embeddings_for_CFA_FA_SUM.append(model2.encode(i["FA_Summary"]))
        if i["FA_Summary"]== None:
            print("found it\n\n",i)
        else:
            list1.append(model2.encode(i["FA_Summary"]))
    return list1

embeddings_for_CFA_FA_SUM = get_embeddings(JIRA_dict,model2)
embeddings_for_CFA_FA_SUM

#embeddings_for_CFA_FA_SUM

[array([0.1781169 , 0.10245991, 0.17204593, ..., 0.12546341, 0.7815531 ,
        0.23097427], dtype=float32),
 array([-0.52057916, -0.2647914 ,  0.4103156 , ...,  0.35397267,
        -0.00433964,  0.49600923], dtype=float32),
 array([-0.6669607 , -0.4860252 ,  0.2999727 , ...,  0.16649497,
        -0.5576712 , -0.10041054], dtype=float32),
 array([-0.40678805, -0.24851549, -0.03225041, ...,  0.26018184,
         0.31432232,  0.44544402], dtype=float32),
 array([-0.16990508,  0.02678629,  0.6249517 , ..., -0.21526927,
         0.05254105,  0.53708076], dtype=float32),
 array([-1.2976966 , -0.97298235,  0.57161033, ..., -0.3009566 ,
        -0.24809226,  0.622274  ], dtype=float32),
 array([-0.15967186, -0.06753741, -0.30263123, ..., -0.06213294,
         0.33339718,  0.4781374 ], dtype=float32),
 array([-0.40051737, -0.38674912, -0.14741886, ...,  0.34926838,
        -0.10121147,  0.25075036], dtype=float32),
 array([-1.0292584 , -0.560025  ,  0.5550643 , ...,  0.37525722,
        -0.16

In [95]:
CFA_failure['FA_Summary_Embeddings'] = embeddings_for_CFA_FA_SUM


C:\Users\1000311006\AppData\Local\Temp\ipykernel_53364\3261415545.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CFA_failure['FA_Summary_Embeddings'] = embeddings_for_CFA_FA_SUM


# Ingestion Pipeline

In [43]:
from llama_index.core import Document, Settings

docs = [
    Document(
        text=issue["FA_Summary"],
        metadata={"JIRA_Number": issue["Jira_Number"]}
        ) 
    for issue in JIRA_dict]

docs

[Document(id_='31a73af7-993c-4ee7-ba5b-f2580f138f85', embedding=None, metadata={'JIRA_Number': 'CSSDFA-1065'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, text='Load switch cracked.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'),
 Document(id_='6bd7d209-2380-4f11-8872-ef6681632499', embedding=None, metadata={'JIRA_Number': 'RMAFA-5903'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, text='Write and then read at different temperatures causes issues with this memory.\r\nRead-all passed @ 25 degree.\r\nFail to read random LBAs @ -25 degree. ', mimetype='text/plain', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'),
 Document(id_='5db03858-7c71-4f6f-b75f-a67b62f48dfb', embedding=None, metadata={'JIRA

In [117]:
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

In [ ]:
'''
from llama_index.vector_stores.elasticsearch import ElasticsearchStore
es_vector_store = ElasticsearchStore(
    index_name = "jira-fa-summary",
    vector_field="FA_Summary_vector",
    text_field="FA_Summary",
    #es_cloud_id=ELASTIC_CLOUD_ID,
    #es_api_key = ELASTIC_API_KEY
)
'''

In [48]:
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.ingestion import IngestionPipeline
from llama_index.embeddings.ollama import OllamaEmbedding

embedding_model = OllamaEmbedding("mistral:latest")

pipeline = IngestionPipeline(
    transformations = [
        SentenceSplitter(chunk_size=250,chunk_overlap = 20),
        embedding_model,
    ]
)

pipeline.run(docs)


Parsing nodes: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]


In [50]:
from llama_index.core import VectorStoreIndex, QueryBundle, Response, Settings
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.llms.ollama import Ollama


local_llm = Ollama(model="mistral:latest")
Settings.embed_model= OllamaEmbedding("mistral:latest")

In [49]:
nodes

[]